export const ParseExpressionTokensAndKeysSamples = [
  {
    license_expression: "apache OR apache-2.0",
    tokens: ["apache", " ", "OR", " ", "apache-2.0"],
    keys: ["apache", "apache-2.0"],
  },
  {
    license_expression: "(mit OR gpl-3.0) AND mit AND gpl-3.0",
    tokens: [
      "",
      "(",
      "mit",
      " ",
      "OR",
      " ",
      "gpl-3.0",
      ")",
      "",
      " ",
      "AND",
      " ",
      "mit",
      " ",
      "AND",
      " ",
      "gpl-3.0",
    ],
    keys: ["mit", "gpl-3.0", "mit", "gpl-3.0"],
  },
  {
    license_expression:
      "(gpl-2.0 WITH font-exception-gpl OR ofl-1.1) AND mit AND apache-2.0",
    tokens: [
      "",
      "(",
      "gpl-2.0",
      " ",
      "WITH",
      " ",
      "font-exception-gpl",
      " ",
      "OR",
      " ",
      "ofl-1.1",
      ")",
      "",
      " ",
      "AND",
      " ",
      "mit",
      " ",
      "AND",
      " ",
      "apache-2.0",
    ],
    keys: ["gpl-2.0", "font-exception-gpl", "ofl-1.1", "mit", "apache-2.0"],
  },
  {
    license_expression:
      "(gpl-2.0 WITH (font-exception-gpl OR ofl-1.1) AND bsd-new) OR (mit AND apache-2.0)",
    tokens: [
      "",
      "(",
      "gpl-2.0",
      " ",
      "WITH",
      " ",
      "",
      "(",
      "font-exception-gpl",
      " ",
      "OR",
      " ",
      "ofl-1.1",
      ")",
      "",
      " ",
      "AND",
      " ",
      "bsd-new",
      ")",
      "",
      " ",
      "OR",
      " ",
      "",
      "(",
      "mit",
      " ",
      "AND",
      " ",
      "apache-2.0",
      ")",
      "",
    ],
    keys: [
      "gpl-2.0",
      "font-exception-gpl",
      "ofl-1.1",
      "bsd-new",
      "mit",
      "apache-2.0",
    ],
  },
];

export const SubExpressionsSamples = [
  {
    license_expression:
      "apache-2.0 AND (mit AND json) AND (apache-2.0 AND bsd-simplified AND bsd-new AND cc0-1.0 AND cddl-1.0) AND (cddl-1.0 AND bsd-new) AND (bsd-new AND epl-2.0 AND elastic-license-v2) AND (bsd-new AND json AND lgpl-2.0 AND mit AND gpl-2.0 AND universal-foss-exception-1.0)",
    subExpressions: [
      "apache-2.0",
      "mit AND json",
      "apache-2.0 AND bsd-simplified AND bsd-new AND cc0-1.0 AND cddl-1.0",
      "cddl-1.0 AND bsd-new",
      "bsd-new AND epl-2.0 AND elastic-license-v2",
      "bsd-new AND json AND lgpl-2.0 AND mit AND gpl-2.0 AND universal-foss-exception-1.0",
    ],
  },
  {
    license_expression:
      "apache-2.0 AND cc0-1.0 AND mit AND (lgpl-2.1 AND bsd-new AND unknown-license-reference) AND bsd-new AND (mit AND apache-2.0 AND bsd-new) AND (ofl-1.1 AND mit AND cc-by-3.0) AND (mit AND cc0-1.0) AND (mit AND apache-2.0) AND (mit AND gpl-3.0) AND ((mit OR gpl-3.0) AND mit AND gpl-3.0) AND ofl-1.1 AND (ofl-1.1 AND proprietary-license) AND isc AND (bsd-new AND bsd-simplified) AND unknown AND (apache-2.0 AND isc) AND (apache-2.0 AND mit) AND ((gpl-2.0 WITH font-exception-gpl OR ofl-1.1) AND apache-2.0) AND (apache-2.0 AND bsd-new AND bsd-simplified AND cc-by-3.0 AND cc0-1.0 AND gpl-3.0 AND isc AND lgpl-2.1 AND mit AND ofl-1.1 AND unknown-license-reference AND other-copyleft AND other-permissive AND unknown)",
    subExpressions: [
      "apache-2.0",
      "cc0-1.0",
      "mit",
      "lgpl-2.1 AND bsd-new AND unknown-license-reference",
      "bsd-new",
      "mit AND apache-2.0 AND bsd-new",
      "ofl-1.1 AND mit AND cc-by-3.0",
      "mit AND cc0-1.0",
      "mit AND apache-2.0",
      "mit AND gpl-3.0",
      "(mit OR gpl-3.0) AND mit AND gpl-3.0",
      "ofl-1.1",
      "ofl-1.1 AND proprietary-license",
      "isc",
      "bsd-new AND bsd-simplified",
      "unknown",
      "apache-2.0 AND isc",
      "apache-2.0 AND mit",
      "(gpl-2.0 WITH font-exception-gpl OR ofl-1.1) AND apache-2.0",
      "apache-2.0 AND bsd-new AND bsd-simplified AND cc-by-3.0 AND cc0-1.0 AND gpl-3.0 AND isc AND lgpl-2.1 AND mit AND ofl-1.1 AND unknown-license-reference AND other-copyleft AND other-permissive AND unknown",
    ],
  },
  {
    license_expression:
      "(gpl-2.0 WITH font-exception-gpl OR ofl-1.1) AND apache-2.0",
    subExpressions: [
      "gpl-2.0 WITH font-exception-gpl OR ofl-1.1",
      "apache-2.0",
    ],
  },
  {
    license_expression: "apache OR apache-2.0",
    subExpressions: ["apache", "apache-2.0"],
  },
  {
    license_expression: "(mit OR gpl-3.0) AND mit AND gpl-3.0",
    subExpressions: ["mit OR gpl-3.0", "mit", "gpl-3.0"],
  },
  {
    license_expression: "apache-2.0 AND (mit AND json)",
    subExpressions: ["apache-2.0", "mit AND json"],
  },
];

export const FilterSpdxKeySamples = {
  keys: [
    "MIT",
    "Apache-2.0 ",
    "Apache-2.0  OR GPL-2.0-only",
    "License-scancode-unknown",
    "License-scancode-somekey",
    "License-scancode-adrian",
    "License-scancode-996-icu-1.0",
    "LicenseRef-scancode-unknown",
    "LicenseRef-scancode-somekey",
    "LicenseRef-scancode-adrian",
    "LicenseRef-scancode-996-icu-1.0",
  ],
  filtered: ["MIT", "Apache-2.0 ", "Apache-2.0  OR GPL-2.0-only"],
};
