import {
  EmailUrlFlatFileAttributes,
  InfoFlatFileAttributes,
} from "../../../src/services/models/flatFile";
import { EmailAttributes } from "../../../src/services/models/email";
import { UrlAttributes } from "../../../src/services/models/url";

export const EmailUrlInfoSamples: {
  jsonFileName: string;
  expectedEmails: EmailAttributes[];
  expectedUrls: UrlAttributes[];
  expectedFlatFiles: (InfoFlatFileAttributes & EmailUrlFlatFileAttributes)[];
}[] = [
  {
    jsonFileName: "email_url_info.json",
    expectedEmails: [
      {
        id: 1,
        fileId: 3,
        email: "ws@tools.de",
        start_line: 412,
        end_line: 412,
      },
      {
        id: 2,
        fileId: 4,
        email: "j@w1.fi",
        start_line: 3,
        end_line: 3,
      },
    ],
    expectedUrls: [
      {
        id: 1,
        fileId: 3,
        url: "http://www.cornfed.com/",
        start_line: 17,
        end_line: 17,
      },
    ],
    expectedFlatFiles: [
      {
        type: "directory",
        name: "basic",
        extension: "",
        date: null,
        size: 57066,
        sha1: null,
        md5: null,
        file_count: 6,
        mime_type: null,
        file_type: null,
        programming_language: null,
        is_binary: false,
        is_text: false,
        is_archive: false,
        is_media: false,
        is_source: false,
        is_script: false,
        email: [],
        email_start_line: [],
        email_end_line: [],
        url: [],
        url_start_line: [],
        url_end_line: [],
      },
      {
        type: "directory",
        name: "dir2",
        extension: "",
        date: null,
        size: 36457,
        sha1: null,
        md5: null,
        file_count: 2,
        mime_type: null,
        file_type: null,
        programming_language: null,
        is_binary: false,
        is_text: false,
        is_archive: false,
        is_media: false,
        is_source: false,
        is_script: false,
        email: [],
        email_start_line: [],
        email_end_line: [],
        url: [],
        url_start_line: [],
        url_end_line: [],
      },
      {
        type: "directory",
        name: "subdir",
        extension: "",
        date: null,
        size: 36457,
        sha1: null,
        md5: null,
        file_count: 2,
        mime_type: null,
        file_type: null,
        programming_language: null,
        is_binary: false,
        is_text: false,
        is_archive: false,
        is_media: false,
        is_source: false,
        is_script: false,
        email: [],
        email_start_line: [],
        email_end_line: [],
        url: [],
        url_start_line: [],
        url_end_line: [],
      },
      {
        type: "file",
        name: "bcopy.s",
        extension: ".s",
        date: "2015-06-19",
        size: 32452,
        sha1: "99f20eafc7b7e1c8e21bced55c8cdd05339bec77",
        md5: "e1c66adaf6b8aa90e348668ac4869a61",
        file_count: 0,
        mime_type: "text/x-c",
        file_type: "C source, ASCII text, with CRLF line terminators",
        programming_language: "GAS",
        is_binary: false,
        is_text: true,
        is_archive: false,
        is_media: false,
        is_source: true,
        is_script: false,
        email: [["ws@tools.de"]],
        email_start_line: [[412]],
        email_end_line: [[412]],
        url: [["http://www.cornfed.com/"]],
        url_start_line: [[17]],
        url_end_line: [[17]],
      },
      {
        type: "file",
        name: "main.c",
        extension: ".c",
        date: "2015-06-19",
        size: 1940,
        sha1: "35017ed9762bdc9d16054a40ceefdda8b362083a",
        md5: "8d0a3b3fe1c96a49af2a66040193291b",
        file_count: 0,
        mime_type: "text/x-c",
        file_type: "C source, ASCII text",
        programming_language: "C",
        is_binary: false,
        is_text: true,
        is_archive: false,
        is_media: false,
        is_source: true,
        is_script: false,
        email: [["j@w1.fi"]],
        email_start_line: [[3]],
        email_end_line: [[3]],
        url: [],
        url_start_line: [],
        url_end_line: [],
      },
    ],
  },
  {
    jsonFileName: "minimal.json",
    expectedEmails: [],
    expectedUrls: [],
    expectedFlatFiles: [
      {
        type: "directory",
        name: "manifests",
        extension: "",
        date: "",
        size: null,
        sha1: "",
        md5: "",
        file_count: null,
        mime_type: "",
        file_type: "",
        programming_language: "",
        is_binary: null,
        is_text: null,
        is_archive: null,
        is_media: null,
        is_source: null,
        is_script: null,
        email: [],
        email_start_line: [],
        email_end_line: [],
        url: [],
        url_start_line: [],
        url_end_line: [],
      },
      {
        type: "file",
        name: "copyright",
        extension: "",
        date: "",
        size: null,
        sha1: "",
        md5: "",
        file_count: null,
        mime_type: "",
        file_type: "",
        programming_language: "",
        is_binary: null,
        is_text: null,
        is_archive: null,
        is_media: null,
        is_source: null,
        is_script: null,
        email: [],
        email_start_line: [],
        email_end_line: [],
        url: [],
        url_start_line: [],
        url_end_line: [],
      },
      {
        type: "file",
        name: "FirebaseAnalytics.podspec.json",
        extension: ".json",
        date: "",
        size: null,
        sha1: "",
        md5: "",
        file_count: null,
        mime_type: "",
        file_type: "",
        programming_language: "",
        is_binary: null,
        is_text: null,
        is_archive: null,
        is_media: null,
        is_source: null,
        is_script: null,
        email: [],
        email_start_line: [],
        email_end_line: [],
        url: [],
        url_start_line: [],
        url_end_line: [],
      },
    ],
  },
];
